### PR TITLE
Avoid locking for put methods for RE2. Fixes #46

### LINKED ISSUE #46: Thoughts on synchronized access on RE2 instances
We've recently been doing some profiling on one of our applications that uses `re2j` quite heavily, and we're noticing a decent amount of thread contention coming from `RE2` when doing concurrent patten matching (i.e. multiple threads using the same `Pattern` instance).

Both `RE2#get` and `RE2#put` synchronize access on the monitor to obtain either a cached `Machine` instance or instantiate a new one if there are none that already exist.

Here's a small example that when run demonstrates the blocking thread behavior:

```java
public class ThreadContentionExample {

  private static final int THREADS = 20;
  private static final Pattern PATTERN = Pattern.compile("\\w+://.*");

  public static void main(String ...args) throws InterruptedException {
    Thread[] threads = new Thread[THREADS];
    for (int i = 0; i < THREADS; i++) {
      Thread thread = new Thread() {
        @Override public void run() {
          while (true) {
            PATTERN.matcher("https://www.google.com").matches();
          }
        }
      };
      thread.start();
      threads[i] = thread;
    }

    for (Thread thread : threads) {
      thread.join();
    }
  }
}
```

The thread profile (via YourKit) looks as follows:

screen shot 2018-02-12 at 11 00 38 am

I did some JMH profiling with various other concurrent data structures, but it seems like all have _slightly_ worse off performance than the current implementation at lower thread counts (within error bounds anyway). A `ConcurrentLinkedQueue` or `Dequeue` seems to be slightly more performant at higher thread counts. However, even if they _were_ better, many of these more "exotic" classes are not available in GWT anyway or they're at a higher JDK language level ([re2j uses 1.6 features now](https://github.com/google/re2j/blob/master/pom.xml#L63)), so I think that precludes them from use.

That said, I was wondering if there were any thoughts how this synchronization bottleneck could be removed, or at least improved a little, in the case that there are many threads accessing the same `Pattern` instance?

Our current approach is to just use `ThreadLocal` `Pattern`s in our application code (as we have bounded thread pools). I see that the `ThreadLocal` approach was adopted in re2j too, but it lead to some memory leaks, so it was [reverted](https://github.com/google/re2j/pull/43).

This definitely _isn't_ a dealbreaker for us, and it's not really a bug either, just food for thought.

`Re2j` has been great! Thanks!

### PR DESCRIPTION
**Pull request by charlesmunger**
The locking could be avoided entirely by allocating wrapper objects for the stack nodes, but I'm not sure if that's desirable. I've also provided another approach that is more complex but offers lock-freedom when the cache is empty.

### CODE REVIEW

**Comment by alandonovan** [comment]
A commit message for a change to introduce a lock-free concurrent data structure needs to say a lot more about background, problem, alternative solutions, technical explanation, and benchmarks than the commit message for this change does.

**Comment by charlesmunger** [comment]
I've updated the commit description. I am not sure how to resolve the GWT failure.

File: java/com/google/re2j/Machine.java [hunk 1]
```diff
@@ -99,6 +99,8 @@ public String toString() {
   private int[] matchcap;
   private int ncap;
 
+  Machine next;
```
Comment (alandonovan) [inline java/com/google/re2j/Machine.java:102]: Document the role of this field (a lock-free linked stack used as a free pool).

File: java/com/google/re2j/RE2.java [hunk 2]
```diff
@@ -213,25 +214,43 @@ int numberOfCapturingGroups() {
   // get() returns a machine to use for matching |this|.  It uses |this|'s
   // machine cache if possible, to avoid unnecessary allocation.
   Machine get() {
+    // Treiber stack (if reusing nodes) suffers from ABA problem on pop. Avoid by unlinking the
+    // entire stack, and stashing it in a pop-only stack guarded by a lock. This also reduces
+    // contention on the AtomicReference between putters and the getter.
     synchronized (this) {
-      if (!machine.isEmpty()) {
-        return machine.remove();
+      if (toGet == null) {
```
Comment (alandonovan) [inline java/com/google/re2j/RE2.java:221]: // Get batch of free machines from lock-free stack.

File: java/com/google/re2j/RE2.java [hunk 3]
```diff
@@ -213,25 +214,43 @@ int numberOfCapturingGroups() {
   // get() returns a machine to use for matching |this|.  It uses |this|'s
   // machine cache if possible, to avoid unnecessary allocation.
   Machine get() {
+    // Treiber stack (if reusing nodes) suffers from ABA problem on pop. Avoid by unlinking the
```
Comment (alandonovan) [inline java/com/google/re2j/RE2.java:217]: Before you get into subtleties, explain what this code does:

// Pop machine from head of toGet free list.
// (Grab a batch from the lock-free stack if empty.)

File: java/com/google/re2j/RE2.java [hunk 4]
```diff
@@ -213,25 +214,43 @@ int numberOfCapturingGroups() {
...
+    // entire stack, and stashing it in a pop-only stack guarded by a lock. This also reduces
+    // contention on the AtomicReference between putters and the getter.
```
Comment (alandonovan) [inline java/com/google/re2j/RE2.java:219]: > reduces contention

How is that? Calls to get must incur a semaphore (exclusive lock).

File: java/com/google/re2j/RE2.java [hunk 5]
```diff
@@ -213,25 +214,43 @@ int numberOfCapturingGroups() {
...
 
   // put() returns a machine to |this|'s machine cache.  There is no attempt to
   // limit the size of the cache, so it will grow to the maximum number of
   // simultaneous matches run using |this|.  (The cache empties when |this|
-  // gets garbage collected.)
-  synchronized void put(Machine m) {
-    machine.add(m);
+  // gets garbage collected or reset is called)
+  void put(Machine m) {
+    while (true) {
```
Comment (alandonovan) [inline java/com/google/re2j/RE2.java:247]: do {
  ...
} while (!pooled.compareAndSet(head, m);

File: java/com/google/re2j/RE2.java (hunk 4 above)
Comment (charlesmunger) [reply java/com/google/re2j/RE2.java:219]: Having the two stacks and batch moves between them means that there's reduced CAS traffic on the AtomicReference, because getters either do a read (empty stack) or pop from their own stack, or import a whole batch, which amortizes the CAS on get.

Comment (alandonovan) [reply java/com/google/re2j/RE2.java:219]: Right, but before reaching the read, they must first enter a synchronized block, whose semaphore requires an atomic decrement. How does the performance compare to a single stack?

Comment (charlesmunger) [reply java/com/google/re2j/RE2.java:219]: I can't use a single stack without allocating a new object per put(). That would make the whole system lock-free, but would also mean allocating on every call (once there's more than one concurrent call ever).

Or I could use a single stack and guard the pop section with a lock - but this would mean locking *and* atomic operations on every get() call. You would, however, be able to use a double-checked-locking approach to avoid synchronization if the pool is empty:

```java
    Machine head = machine.get();
    if (head != null) {
      // Lock necessary here because we're reusing nodes - otherwise suffer from ABA problem
      synchronized (this) {
        while (true) {
          head = machine.get();
          if (head == null) {
            break;
          }
          if (machine.compareAndSet(head, head.next)) {
            head.next = null;
            return head;
          }
          head = machine.get();
        }
      }
    }
```

That approach felt a bit more complicated and seemed like more of a departure from the existing code, but if you prefer it I can use it instead. Actual performance cost depends on target architecture, amount of contention, etc. The checked-in benchmarks for RE2 don't exercise threads, and even if there were concurrent benchmarks it'd be hard to generalize them across platforms.

**Comment by charlesmunger** [comment]
With my change:
```
Benchmark                           (impl)  (regex)  (repeats)  Mode  Cnt      Score      Error  Units
BenchmarkBacktrack.matched             JDK      N/A          5  avgt    5      0.546 ±    0.018  us/op
BenchmarkBacktrack.matched             JDK      N/A         10  avgt    5     18.374 ±    2.611  us/op
BenchmarkBacktrack.matched             JDK      N/A         15  avgt    5    699.405 ±   26.860  us/op
BenchmarkBacktrack.matched             JDK      N/A         20  avgt    5  27318.340 ± 3808.455  us/op
BenchmarkBacktrack.matched            RE2J      N/A          5  avgt    5      0.926 ±    0.049  us/op
BenchmarkBacktrack.matched            RE2J      N/A         10  avgt    5      2.876 ±    0.234  us/op
BenchmarkBacktrack.matched            RE2J      N/A         15  avgt    5      5.837 ±    0.156  us/op
BenchmarkBacktrack.matched            RE2J      N/A         20  avgt    5      9.333 ±    0.839  us/op
BenchmarkCompile.compile               JDK     DATE        N/A  avgt    5    657.609 ±   30.343  ns/op
BenchmarkCompile.compile               JDK    EMAIL        N/A  avgt    5    209.188 ±    4.231  ns/op
BenchmarkCompile.compile               JDK    PHONE        N/A  avgt    5    320.981 ±   13.061  ns/op
BenchmarkCompile.compile               JDK   RANDOM        N/A  avgt    5   1018.124 ±   18.428  ns/op
BenchmarkCompile.compile               JDK   SOCIAL        N/A  avgt    5    283.678 ±   12.677  ns/op
BenchmarkCompile.compile               JDK   STATES        N/A  avgt    5   1321.436 ±  141.171  ns/op
BenchmarkCompile.compile              RE2J     DATE        N/A  avgt    5   2649.448 ±   32.502  ns/op
BenchmarkCompile.compile              RE2J    EMAIL        N/A  avgt    5    959.094 ±   24.034  ns/op
BenchmarkCompile.compile              RE2J    PHONE        N/A  avgt    5   1513.050 ±  100.937  ns/op
BenchmarkCompile.compile              RE2J   RANDOM        N/A  avgt    5   5404.207 ±  118.983  ns/op
BenchmarkCompile.compile              RE2J   SOCIAL        N/A  avgt    5   1067.002 ±   11.441  ns/op
BenchmarkCompile.compile              RE2J   STATES        N/A  avgt    5   7525.129 ±  638.113  ns/op
BenchmarkFullMatch.matched             JDK      N/A        N/A  avgt    5    102.320 ±    7.576  ns/op
BenchmarkFullMatch.matched            RE2J      N/A        N/A  avgt    5    486.554 ±   22.257  ns/op
BenchmarkFullMatch.notMatched          JDK      N/A        N/A  avgt    5     61.846 ±    4.451  ns/op
BenchmarkFullMatch.notMatched         RE2J      N/A        N/A  avgt    5    437.695 ±   21.006  ns/op
BenchmarkSubMatch.findPhoneNumbers     JDK      N/A        N/A  avgt    5      3.030 ±    0.152  ms/op
BenchmarkSubMatch.findPhoneNumbers    RE2J      N/A        N/A  avgt    5     13.751 ±    1.253  ms/op
```

Without:
```
Benchmark                           (impl)  (regex)  (repeats)  Mode  Cnt      Score      Error  Units
BenchmarkBacktrack.matched             JDK      N/A          5  avgt    5      0.563 ±    0.023  us/op
BenchmarkBacktrack.matched             JDK      N/A         10  avgt    5     19.759 ±    0.452  us/op
BenchmarkBacktrack.matched             JDK      N/A         15  avgt    5    717.583 ±   20.566  us/op
BenchmarkBacktrack.matched             JDK      N/A         20  avgt    5  30465.382 ± 1059.643  us/op
BenchmarkBacktrack.matched            RE2J      N/A          5  avgt    5      1.052 ±    0.015  us/op
BenchmarkBacktrack.matched            RE2J      N/A         10  avgt    5      3.245 ±    0.226  us/op
BenchmarkBacktrack.matched            RE2J      N/A         15  avgt    5      6.825 ±    0.196  us/op
BenchmarkBacktrack.matched            RE2J      N/A         20  avgt    5     11.549 ±    1.129  us/op
BenchmarkCompile.compile               JDK     DATE        N/A  avgt    5    785.358 ±   20.005  ns/op
BenchmarkCompile.compile               JDK    EMAIL        N/A  avgt    5    255.705 ±   13.109  ns/op
BenchmarkCompile.compile               JDK    PHONE        N/A  avgt    5    385.573 ±   15.514  ns/op
BenchmarkCompile.compile               JDK   RANDOM        N/A  avgt    5   1195.869 ±  106.540  ns/op
BenchmarkCompile.compile               JDK   SOCIAL        N/A  avgt    5    343.272 ±   12.794  ns/op
BenchmarkCompile.compile               JDK   STATES        N/A  avgt    5   1569.633 ±  164.334  ns/op
BenchmarkCompile.compile              RE2J     DATE        N/A  avgt    5   3208.025 ±  225.822  ns/op
BenchmarkCompile.compile              RE2J    EMAIL        N/A  avgt    5   1136.255 ±   71.899  ns/op
BenchmarkCompile.compile              RE2J    PHONE        N/A  avgt    5   1803.507 ±  106.871  ns/op
BenchmarkCompile.compile              RE2J   RANDOM        N/A  avgt    5   6472.174 ±  236.211  ns/op
BenchmarkCompile.compile              RE2J   SOCIAL        N/A  avgt    5   1273.778 ±   17.144  ns/op
BenchmarkCompile.compile              RE2J   STATES        N/A  avgt    5   9010.883 ±  734.132  ns/op
BenchmarkFullMatch.matched             JDK      N/A        N/A  avgt    5    119.059 ±    6.297  ns/op
BenchmarkFullMatch.matched            RE2J      N/A        N/A  avgt    5    573.888 ±   15.052  ns/op
BenchmarkFullMatch.notMatched          JDK      N/A        N/A  avgt    5     69.659 ±    2.206  ns/op
BenchmarkFullMatch.notMatched         RE2J      N/A        N/A  avgt    5    515.374 ±   25.949  ns/op
BenchmarkSubMatch.findPhoneNumbers     JDK      N/A        N/A  avgt    5      3.509 ±    0.640  ms/op
BenchmarkSubMatch.findPhoneNumbers    RE2J      N/A        N/A  avgt    5     15.647 ±    2.617  ms/op
```
Looks like an overall improvement, even for the single thread case. Avoiding the lock and avoiding the arraydeque bookkeeping probably helps.

**Comment by alandonovan** [comment]
Nice; looks like about a 10% improvement across the board in the single threaded case. That probably paid for your time in CPUs already, never mind contention.  : )

I don't see the latest changes we discussed yet. Ping me when they're ready.

File: java/com/google/re2j/Machine.java [hunk 6]
```diff
@@ -99,6 +99,9 @@ public String toString() {
   private int[] matchcap;
   private int ncap;
```
Comment (alandonovan) [inline java/com/google/re2j/Machine.java:100]: Add a reminder to add fields both here and to the copy constructor.

File: java/com/google/re2j/RE2.java [hunk 7]
```diff
@@ -213,25 +211,41 @@ int numberOfCapturingGroups() {
...
+    pooled.set(null);
   }
 
   // put() returns a machine to |this|'s machine cache.  There is no attempt to
   // limit the size of the cache, so it will grow to the maximum number of
   // simultaneous matches run using |this|.  (The cache empties when |this|
-  // gets garbage collected.)
-  synchronized void put(Machine m) {
-    machine.add(m);
+  // gets garbage collected or reset is called)
```
Comment (alandonovan) [inline java/com/google/re2j/RE2.java:230]: Missing period.

File: java/com/google/re2j/RE2.java [hunk 8]
```diff
@@ -213,25 +211,41 @@ int numberOfCapturingGroups() {
...
+  void put(Machine m, boolean isNewNode) {
```
Comment (alandonovan) [inline java/com/google/re2j/RE2.java:231]: isNew

("node" is not a defined term here)

**Review by alandonovan — COMMENTED** [review]
Looks good; thanks for the optimization, and for your patience.

**Comment by charlesmunger** [comment]
Any updates on blockers for this CL?

**Comment by sjamesr** [comment]
This change should work against gwt 2.9.0, which you can specify in the `build.gradle` file.

**Comment by charlesmunger** [comment]
Updated, and tests now pass.
